.TH uftp_keymgt 1 "22 April 2020" "UFTP 5.0"
.SH NAME
uftp_keymgt - Encrypted UDP based ftp with multicast - key management utility
.SH SYNOPSIS
uftp_keymgt [ -m ] [ key_file [ key_file ...] ]

uftp_keymgt [ -m ] -g { rsa:key_length | ec:curve } key_file

uftp_keymgt [ -m ] -d key_file

.SH DESCRIPTION
.P
.B uftp_keymgt
is a utility for creating, viewing, and deleting RSA and EC private keys used by the UFTP suite.
Although keys can be generated on the fly by
.BR uftp (1),
.BR uftpd (1),
and
.BR uftpproxyd (1),
this utility gives a more straightforward way of doing so without having to kick off a dummy process just to create/view a key.

The definition of \fIkey_file\fP is dependent on the crypto library UFTP is compiled to use.

On Windows systems, UFTP uses CNG (Cryptography API: Next Generation).
Under CNG, all RSA and EC private keys must be stored in a key container (technically only keys used to sign data, but for UFTP\(aqs purposes this is the case).
Key containers are internal to Windows, and each user (and the system) has its own set of key containers.
In this case, key_file is actually the name of the key container.

All other systems use OpenSSL for the crypto library (although under Windows UFTP can be also be built to use it).
In this case, key_file specifies a file name where the RSA or ECDSA private key is stored unencrypted in PEM format (the OS is expected to protect this file).

The \fB\-g\fP option is used to generate a key of a given type and store it in the given key_file.
The key size and key fingerprint are then printed.
Under OpenSSL, a key can actually be generated by the
.BR openssl (1)
command line utility, although you\(aqll still need to run uftp_keymgt on it to see the fingerprint.

The \fB\-d\fP option is available only on Windows systems using CNG.
It deletes the key container specified by key_file.

When neither \fB\-g\fP or \fB\-d\fP are specified, the type and fingerprint of all keys listed are printed.
If no keys are specified under Windows with CNG, the private key for all key containers for the current user are printed.
Note that some key containers may exist that an application other than UFTP is using, and some of those may not have an RSA or EC private key.

.SH OPTIONS
.P
The following options are supported:
.TP
\fB\-g\fP \ {\ \fBrsa:\fP\fIkey_length\fP | \fBec:\fP\fIcurve\fP } \fIkey_file\fP
Specifies the type of new key and the key_file to store it in.
New keys are specified as either \fBrsa:\fP\fIkey_length\fP, which creates an RSA private key \fIkey_length\fP bits wide, or as \fBec:\fP\fIcurve\fP, which creates an EC key using the curve "\fIcurve\fP".

The supported EC curves are secp256r1 (prime256v1), secp384r1, and secp521r1.

.TP
.BI \-d \ key_file
Specifies the Windows key container to delete.
.TP
.B \-m
For Windows systems using CNG, private keys are normally stored in the key container of the running user.
Specifying this option stores keys in the system key container.
On non-Windows systems, this option has no effect.
.SH EXIT STATUS
.P
The following exit values are returned:
.TP
0
The command completed successfully.
.TP
1
An invalid command line parameter was specified.
.SH SEE ALSO
.BR uftp (1),
.BR uftpd (1),
.BR uftpproxyd (1).
.SH NOTES
.P
The latest version of UFTP can be found at http://uftp-multicast.sourceforge.net.
UFTP is covered by the GNU General Public License.
Commercial licenses and support are available from Dennis Bush (bush@tcnj.edu).
